name: Brucards
description: An Inclusive way to Drink Card Game

version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  provider: ^4.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true